name: Node.js CI

on:
  push:
    branches: [main]
  # pull_request:
  #   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3.3.0
      - name: Node.js ${{ matrix.node-version }} -- npm install
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # - run: npm i -g pnpm
      # - run: pnpm install
      # - run: pnpm build
      # - name: Debug SSH Secrets

      #   run: |
      #     echo "Host: ${{ secrets.SSH_HOST }}"
      #     echo "Username: ${{ secrets.SSH_USERNAME }}"
      #     echo "Port: ${{ secrets.SSH_PORT }}"

      # - name: execute remote ssh & deploy backend server
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     passphrase: ${{ secrets.SSH_PASSPHRASE }}
      #     port: ${{ secrets.SSH_PORT }}
      #     script: |
      #       whoami

      # - name: SSH and NPM Install
      #   uses: appleboy/ssh-action@v0.1.4
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     port: ${{ secrets.SSH_PORT }}
      #     passphrase: ${{ secrets.SSH_PASSPHRASE }}
      #     script: whoami
      - name: whoami via ssh
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: whoami
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY}}
