name: Node.js CI

on:
  push:
    branches: [main]
  # pull_request:
  #   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Node.js ${{ matrix.node-version }} -- npm install
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # - run: npm i -g pnpm
      # - run: pnpm install
      # - run: pnpm build
      # - name: Debug SSH Secrets

      #   run: |
      #     echo "Host: ${{ secrets.SSH_HOST }}"
      #     echo "Username: ${{ secrets.SSH_USERNAME }}"
      #     echo "Port: ${{ secrets.SSH_PORT }}"

      - name: ls -a via OPEN SSH Private Key
        uses: fifsky/ssh-action@master
        with:
          command: |
            whoami
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          pass: ${{ secrets.SSH_PASSPHRASE }}
          args: "-tt -vvv"

      # - name: SSH and NPM Install
      #   uses: appleboy/ssh-action@v0.1.7
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     port: ${{ secrets.SSH_PORT }}
      #     passphrase: ${{ secrets.SSH_PASSPHRASE }}
      #     script: whoami
