name: CLICK-STORE CD

on:
  push:
    branches: [main]
  # pull_request:
  #   branches: [main]
  # test
jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [20.x]

    steps:
      # - uses: actions/checkout@v3.3.0
      # - name: Node.js ${{ matrix.node-version }} -- npm install
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: ${{ matrix.node-version }}

      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd c:\click-store\next-test-click-store & git pull & pnpm install & pnpm deploy:prod
